"""Librarian operation router contract tests."""

from __future__ import annotations

from datetime import UTC, datetime

from app.librarian.domain.entities.skill_acquisition_job import SkillAcquisitionJob
from app.librarian.domain.event_enum.collaboration_enums import (
    SkillAcquisitionJobStatus,
)
from app.library.domain.event_enum.item_enums import ItemType
from app.main import app
from app.shared.types.extra_types import JSONValue
from fastapi.testclient import TestClient
from tests.shared.provider_overrides import override_library_provider


class FakeItemSearchService:
    """In-memory search service for librarian operation contract tests."""

    def __init__(self) -> None:
        """Initialize captured search state."""
        self.searched_item_type: ItemType | None = None

    async def search(
        self,
        query: str,
        item_type: ItemType | None = None,
        limit: int = 5,
    ) -> dict[str, JSONValue]:
        """Return one skill recommendation result."""
        self.searched_item_type = item_type
        return {
            "items": [
                {
                    "id": "00000000-0000-4000-8000-000000000321",
                    "item_type": "SKILL",
                    "title": f"Result for {query}",
                    "summary": "Recommended skill.",
                    "category_id": None,
                    "tags": ["strict-json"],
                    "status": "ACTIVE",
                    "score": 1.0,
                    "why_matched": ["title"],
                    "highlights": [f"Result for {query}"],
                    "details_preview": {},
                    "content_char_count": 46,
                    "updated_at": datetime(2026, 5, 12, 10, 5, tzinfo=UTC),
                }
            ],
            "total": 1,
            "limit": limit,
            "offset": 0,
        }


class FakeLibrarianGenerationService:
    """Deterministic librarian candidate service for router contract tests."""

    def generate_skill_candidate(
        self,
        *,
        provider_id: str,
        prompt: str,
        category_id: str | None,
    ) -> dict[str, JSONValue]:
        """Return a deterministic generated skill candidate."""
        used_at = "2026-05-12T10:05:00Z"
        return {
            "id": "draft-skill-candidate",
            "item_type": "SKILL",
            "title": "Generated strict JSON skill",
            "summary": "Candidate generated by librarian.",
            "content": f"Provider {provider_id} generated: {prompt}",
            "category_id": category_id,
            "tags": ["draft", "librarian"],
            "status": "DRAFT",
            "source_type": "LIBRARIAN_CREATED",
            "created_by_type": "LIBRARIAN",
            "created_by_name": "librarian",
            "details": {
                "purpose": prompt,
                "input_schema": {"type": "object"},
                "output_schema": {"type": "object"},
                "required_tools": ["pytest"],
                "risk_level": "LOW",
                "version": "1.0.0",
            },
            "created_at": used_at,
            "updated_at": used_at,
        }


class FakeSkillAcquisitionService:
    """Deterministic durable acquisition job service for router tests."""

    def __init__(self) -> None:
        """Initialize captured job state."""
        self.job = SkillAcquisitionJob(
            id="skill-acquisition-1",
            prompt="Need a browser automation skill",
            agent_name="Hermes",
            project="alexandria-hermes",
            task_summary="Investigate Playwright usage.",
            status=SkillAcquisitionJobStatus.ACCEPTED,
            provider_id="00000000-0000-4000-8000-000000000501",
            librarian_profile_id=None,
            skill_id=None,
            context_id=None,
            result_summary="Skill acquisition job accepted.",
            evidence_urls=[],
            error_message=None,
            created_at=datetime(2026, 5, 18, 17, 30, tzinfo=UTC),
            updated_at=datetime(2026, 5, 18, 17, 30, tzinfo=UTC),
            completed_at=None,
        )

    async def request_job(
        self,
        *,
        prompt: str,
        agent_name: str = "Hermes",
        project: str | None = None,
        task_summary: str | None = None,
        provider_id: str | None = None,
        librarian_profile_id: str | None = None,
    ) -> SkillAcquisitionJob:
        """Return one accepted durable job."""
        self.job = SkillAcquisitionJob(
            id="skill-acquisition-1",
            prompt=prompt,
            agent_name=agent_name,
            project=project,
            task_summary=task_summary,
            status=SkillAcquisitionJobStatus.ACCEPTED,
            provider_id=provider_id,
            librarian_profile_id=librarian_profile_id,
            skill_id=None,
            context_id=None,
            result_summary="Skill acquisition job accepted.",
            evidence_urls=[],
            error_message=None,
            created_at=datetime(2026, 5, 18, 17, 30, tzinfo=UTC),
            updated_at=datetime(2026, 5, 18, 17, 30, tzinfo=UTC),
            completed_at=None,
        )
        return self.job

    async def get_job(self, job_id: str) -> SkillAcquisitionJob:
        """Return the captured job."""
        _ = job_id
        return self.job

    async def complete_with_skill_artifact(self, job_id, artifact):  # type: ignore[no-untyped-def]
        """Return a completed job with sanitized skill and context handles."""
        _ = job_id
        self.job = SkillAcquisitionJob(
            id=self.job.id,
            prompt=self.job.prompt,
            agent_name=self.job.agent_name,
            project=self.job.project,
            task_summary=self.job.task_summary,
            status=SkillAcquisitionJobStatus.COMPLETED,
            provider_id=self.job.provider_id,
            librarian_profile_id=self.job.librarian_profile_id,
            skill_id="00000000-0000-4000-8000-000000000777",
            context_id="00000000-0000-4000-8000-000000000888",
            result_summary=f"Persisted {artifact.title}.",
            evidence_urls=list(artifact.evidence_urls),
            error_message=None,
            created_at=self.job.created_at,
            updated_at=datetime(2026, 5, 18, 17, 31, tzinfo=UTC),
            completed_at=datetime(2026, 5, 18, 17, 31, tzinfo=UTC),
        )
        return self.job


def test_recommend_accepts_json_item_type_string_and_returns_items() -> None:
    """POST /librarians/recommend should accept public item_type enum strings."""
    item_service = FakeItemSearchService()

    def override_item_service() -> FakeItemSearchService:
        return item_service

    with override_library_provider("item_search_service", override_item_service()):
        with TestClient(app, raise_server_exceptions=False) as client:
            response = client.post(
                "/librarians/recommend",
                json={"query": "strict JSON", "item_type": "SKILL", "limit": 1},
            )

    assert response.status_code == 200
    assert response.json() == {
        "items": [
            {
                "id": "00000000-0000-4000-8000-000000000321",
                "item_type": "SKILL",
                "title": "Result for strict JSON",
                "summary": "Recommended skill.",
                "tags": ["strict-json"],
                "status": "ACTIVE",
                "category_id": None,
                "score": 1.0,
                "why_matched": ["title"],
                "highlights": ["Result for strict JSON"],
                "details_preview": {},
                "content_char_count": 46,
                "updated_at": "2026-05-12T10:05:00Z",
            }
        ],
        "total": 1,
        "limit": 1,
        "offset": 0,
    }
    assert item_service.searched_item_type is ItemType.SKILL


def test_skill_acquisition_job_routes_return_sanitized_durable_status() -> None:
    """Skill acquisition routes should create and poll durable sanitized jobs."""
    service = FakeSkillAcquisitionService()

    with override_library_provider("skill_acquisition_service", service):
        with TestClient(app, raise_server_exceptions=False) as client:
            create_response = client.post(
                "/librarians/skill-acquisition-jobs",
                json={
                    "prompt": "Need a browser automation skill",
                    "agent_name": "Hermes",
                    "project": "alexandria-hermes",
                    "task_summary": "Investigate Playwright usage.",
                    "provider_id": "00000000-0000-4000-8000-000000000501",
                },
            )
            status_response = client.get(
                "/librarians/skill-acquisition-jobs/skill-acquisition-1"
            )

    assert create_response.status_code == 202
    assert status_response.status_code == 200
    body = create_response.json()
    serialized = f"{body}{status_response.json()}"
    assert body["id"] == "skill-acquisition-1"
    assert body["status"] == "ACCEPTED"
    assert body["result_available"] is False
    assert body["prompt"] == "Need a browser automation skill"
    assert "SECRET" not in serialized
    assert "api_key" not in serialized


def test_skill_acquisition_completion_route_returns_resume_handles() -> None:
    """Completion route should return persisted skill and context handles."""
    service = FakeSkillAcquisitionService()

    with override_library_provider("skill_acquisition_service", service):
        with TestClient(app, raise_server_exceptions=False) as client:
            response = client.post(
                "/librarians/skill-acquisition-jobs/skill-acquisition-1/complete",
                json={
                    "title": "Browser automation skill",
                    "purpose": "Use browser automation deterministically.",
                    "content": "Use a real browser boundary and stable selectors.",
                    "summary": "Skill persisted from async acquisition.",
                    "tags": ["browser"],
                    "evidence_urls": ["https://example.com/browser"],
                    "source_summary": "Provider returned a sanitized artifact.",
                    "next_steps": ["Apply this skill to the waiting browser task."],
                },
            )

    assert response.status_code == 200
    body = response.json()
    assert {
        "status": body["status"],
        "result_available": body["result_available"],
        "skill_id": body["skill_id"],
        "context_id": body["context_id"],
        "evidence_urls": body["evidence_urls"],
    } == {
        "status": "COMPLETED",
        "result_available": True,
        "skill_id": "00000000-0000-4000-8000-000000000777",
        "context_id": "00000000-0000-4000-8000-000000000888",
        "evidence_urls": ["https://example.com/browser"],
    }


def test_create_skill_candidate_returns_strict_item_response_shape() -> None:
    """POST /librarians/create-skill-candidate should return valid ItemResponse JSON."""

    def override_librarian_service() -> FakeLibrarianGenerationService:
        return FakeLibrarianGenerationService()

    with override_library_provider(
        "librarian_ops_service", override_librarian_service()
    ):
        with TestClient(app, raise_server_exceptions=False) as client:
            response = client.post(
                "/librarians/create-skill-candidate",
                json={
                    "provider_id": "00000000-0000-4000-8000-000000000501",
                    "prompt": "Create a strict JSON skill.",
                    "category_id": "00000000-0000-4000-8000-000000000002",
                },
            )

    assert response.status_code == 200
    body = response.json()
    assert body == {
        "id": "draft-skill-candidate",
        "item_type": "SKILL",
        "title": "Generated strict JSON skill",
        "summary": "Candidate generated by librarian.",
        "content": "Provider 00000000-0000-4000-8000-000000000501 generated: Create a strict JSON skill.",
        "category_id": "00000000-0000-4000-8000-000000000002",
        "tags": ["draft", "librarian"],
        "status": "DRAFT",
        "source_type": "LIBRARIAN_CREATED",
        "created_by_type": "LIBRARIAN",
        "created_by_name": "librarian",
        "details": {
            "purpose": "Create a strict JSON skill.",
            "input_schema": {"type": "object"},
            "output_schema": {"type": "object"},
            "required_tools": ["pytest"],
            "risk_level": "LOW",
            "version": "1.0.0",
        },
        "created_at": body["created_at"],
        "updated_at": body["updated_at"],
    }
    assert isinstance(body["created_at"], str)
    assert body["created_at"] == body["updated_at"]
