"""Librarian operation router contract tests."""

from __future__ import annotations

from datetime import UTC, datetime

from app.library.domain.event_enum.item_enums import ItemType
from tests.shared.provider_overrides import override_library_provider
from app.main import app
from app.shared.types.extra_types import JSONValue
from fastapi.testclient import TestClient


class FakeItemSearchService:
    """In-memory search service for librarian operation contract tests."""

    def __init__(self) -> None:
        """Initialize captured search state."""
        self.searched_item_type: ItemType | None = None

    async def search(
        self,
        query: str,
        item_type: ItemType | None = None,
        limit: int = 5,
    ) -> dict[str, JSONValue]:
        """Return one skill recommendation result."""
        self.searched_item_type = item_type
        return {
            "items": [
                {
                    "id": "00000000-0000-4000-8000-000000000321",
                    "item_type": "SKILL",
                    "title": f"Result for {query}",
                    "summary": "Recommended skill.",
                    "category_id": None,
                    "tags": ["strict-json"],
                    "status": "ACTIVE",
                    "score": 1.0,
                    "why_matched": ["title"],
                    "highlights": [f"Result for {query}"],
                    "details_preview": {},
                    "content_char_count": 46,
                    "updated_at": datetime(2026, 5, 12, 10, 5, tzinfo=UTC),
                }
            ],
            "total": 1,
            "limit": limit,
            "offset": 0,
        }


class FakeLibrarianGenerationService:
    """Deterministic librarian candidate service for router contract tests."""

    def generate_skill_candidate(
        self,
        *,
        provider_id: str,
        prompt: str,
        category_id: str | None,
    ) -> dict[str, JSONValue]:
        """Return a deterministic generated skill candidate."""
        used_at = "2026-05-12T10:05:00Z"
        return {
            "id": "draft-skill-candidate",
            "item_type": "SKILL",
            "title": "Generated strict JSON skill",
            "summary": "Candidate generated by librarian.",
            "content": f"Provider {provider_id} generated: {prompt}",
            "category_id": category_id,
            "tags": ["draft", "librarian"],
            "status": "DRAFT",
            "source_type": "LIBRARIAN_CREATED",
            "created_by_type": "LIBRARIAN",
            "created_by_name": "librarian",
            "details": {
                "purpose": prompt,
                "input_schema": {"type": "object"},
                "output_schema": {"type": "object"},
                "required_tools": ["pytest"],
                "risk_level": "LOW",
                "version": "1.0.0",
            },
            "created_at": used_at,
            "updated_at": used_at,
        }


def test_recommend_accepts_json_item_type_string_and_returns_items() -> None:
    """POST /librarians/recommend should accept public item_type enum strings."""
    item_service = FakeItemSearchService()

    def override_item_service() -> FakeItemSearchService:
        return item_service

    with override_library_provider("item_search_service", override_item_service()):
        with TestClient(app, raise_server_exceptions=False) as client:
            response = client.post(
                "/librarians/recommend",
                json={"query": "strict JSON", "item_type": "SKILL", "limit": 1},
            )

    assert response.status_code == 200
    assert response.json() == {
        "items": [
            {
                "id": "00000000-0000-4000-8000-000000000321",
                "item_type": "SKILL",
                "title": "Result for strict JSON",
                "summary": "Recommended skill.",
                "tags": ["strict-json"],
                "status": "ACTIVE",
                "category_id": None,
                "score": 1.0,
                "why_matched": ["title"],
                "highlights": ["Result for strict JSON"],
                "details_preview": {},
                "content_char_count": 46,
                "updated_at": "2026-05-12T10:05:00Z",
            }
        ],
        "total": 1,
        "limit": 1,
        "offset": 0,
    }
    assert item_service.searched_item_type is ItemType.SKILL


def test_create_skill_candidate_returns_strict_item_response_shape() -> None:
    """POST /librarians/create-skill-candidate should return valid ItemResponse JSON."""

    def override_librarian_service() -> FakeLibrarianGenerationService:
        return FakeLibrarianGenerationService()

    with override_library_provider(
        "librarian_ops_service", override_librarian_service()
    ):
        with TestClient(app, raise_server_exceptions=False) as client:
            response = client.post(
                "/librarians/create-skill-candidate",
                json={
                    "provider_id": "00000000-0000-4000-8000-000000000501",
                    "prompt": "Create a strict JSON skill.",
                    "category_id": "00000000-0000-4000-8000-000000000002",
                },
            )

    assert response.status_code == 200
    body = response.json()
    assert body == {
        "id": "draft-skill-candidate",
        "item_type": "SKILL",
        "title": "Generated strict JSON skill",
        "summary": "Candidate generated by librarian.",
        "content": "Provider 00000000-0000-4000-8000-000000000501 generated: Create a strict JSON skill.",
        "category_id": "00000000-0000-4000-8000-000000000002",
        "tags": ["draft", "librarian"],
        "status": "DRAFT",
        "source_type": "LIBRARIAN_CREATED",
        "created_by_type": "LIBRARIAN",
        "created_by_name": "librarian",
        "details": {
            "purpose": "Create a strict JSON skill.",
            "input_schema": {"type": "object"},
            "output_schema": {"type": "object"},
            "required_tools": ["pytest"],
            "risk_level": "LOW",
            "version": "1.0.0",
        },
        "created_at": body["created_at"],
        "updated_at": body["updated_at"],
    }
    assert isinstance(body["created_at"], str)
    assert body["created_at"] == body["updated_at"]
