"""Shared backend exception catalog."""

from .common_exceptions import (
    RedisExceptionAction,
    RedisExceptionArgValue,
    RedisExceptionAware,
    RedisExceptionDecorator,
    RedisExceptionHandler,
    RedisExceptionKwargs,
    RedisExceptionPayload,
    RedisExceptionPolicy,
    RedisExceptionPolicyMap,
    RedisExceptionRawData,
    RedisExceptionResult,
)
from .exception_decorators import router_exception_status
from .librarian_exceptions import LibrarianDomainError, LibrarianValidationError
from .library_exceptions import (
    CircularCategoryError,
    LibraryCategoryCycleError,
    LibraryDomainError,
    LibraryProviderUnsupportedError,
    LibraryResourceNotFoundError,
    LibraryValidationError,
    NotFoundError,
    UnsupportedProviderError,
    ValidationError,
)
from .memory_compact_exceptions import (
    MemoryCompactDomainError,
    MemoryCompactNotFoundError,
    MemoryCompactValidationError,
)
from .route_exceptions import (
    ARCHIVE_ROUTE_EXCEPTION_MAPPING,
    CONNECTIONS_ROUTE_EXCEPTION_MAPPING,
    CONTEXT_ROUTE_EXCEPTION_MAPPING,
    LIBRARIAN_ROUTE_EXCEPTION_MAPPING,
    LIBRARY_PROVIDER_TEST_EXCEPTION_MAPPING,
    LIBRARY_ROUTE_EXCEPTION_MAPPING,
    MEMORY_COMPACT_ROUTE_EXCEPTION_MAPPING,
    RETRIEVAL_ROUTE_EXCEPTION_MAPPING,
)

__all__ = [
    "ARCHIVE_ROUTE_EXCEPTION_MAPPING",
    "CONNECTIONS_ROUTE_EXCEPTION_MAPPING",
    "CONTEXT_ROUTE_EXCEPTION_MAPPING",
    "LIBRARIAN_ROUTE_EXCEPTION_MAPPING",
    "LIBRARY_PROVIDER_TEST_EXCEPTION_MAPPING",
    "LIBRARY_ROUTE_EXCEPTION_MAPPING",
    "MEMORY_COMPACT_ROUTE_EXCEPTION_MAPPING",
    "RETRIEVAL_ROUTE_EXCEPTION_MAPPING",
    "CircularCategoryError",
    "LibrarianDomainError",
    "LibrarianValidationError",
    "LibraryCategoryCycleError",
    "LibraryDomainError",
    "LibraryProviderUnsupportedError",
    "LibraryResourceNotFoundError",
    "LibraryValidationError",
    "MemoryCompactDomainError",
    "MemoryCompactNotFoundError",
    "MemoryCompactValidationError",
    "NotFoundError",
    "RedisExceptionAction",
    "RedisExceptionArgValue",
    "RedisExceptionAware",
    "RedisExceptionDecorator",
    "RedisExceptionHandler",
    "RedisExceptionKwargs",
    "RedisExceptionPayload",
    "RedisExceptionPolicy",
    "RedisExceptionPolicyMap",
    "RedisExceptionRawData",
    "RedisExceptionResult",
    "UnsupportedProviderError",
    "ValidationError",
    "router_exception_status",
]
