"""Package-level exports for CLI command contracts.

Prefer importing from the concept-owned modules when a caller only needs one
command family; use this package namespace for broad CLI contract surfaces.
"""

from __future__ import annotations

from app.cli_support.contracts.codex_command_contracts import CodexMcpInstallCommand
from app.cli_support.contracts.hermes_command_contracts import (
    HermesBundleCommand,
    HermesConfigureCommand,
    HermesDoctorCommand,
    HermesInstallCommand,
    HermesOnboardCommand,
    HermesPolicyCommand,
    HermesScanCommand,
    HermesSyncCommand,
)
from app.cli_support.contracts.librarian_command_contracts import (
    LibrarianAskCommand,
    LibrarianBriefPreviewCommand,
    LibrarianJobStatusCommand,
    LibrarianOAuthCommand,
    LibrarianProfileActionCommand,
    LibrarianProfileCreateCommand,
    LibrarianProfileUpdateCommand,
    LibrarianProviderActionCommand,
    LibrarianProviderConnectCodexOAuthCommand,
    LibrarianProviderCreateCommand,
    LibrarianRoutePreviewCommand,
    UsageRecordCliCommand,
)
from app.cli_support.contracts.library_command_contracts import (
    FolderIdCommand,
    FoldersCreateCommand,
    FoldersEnsureCommand,
    FoldersListCommand,
    ItemIdCommand,
    LibraryListCommand,
    LibrarySearchCommand,
    PromptDeprecateCommand,
    PromptDiffCommand,
    PromptsListCommand,
    PromptsSearchCommand,
    PromptsUseCommand,
    PromptVersionCommand,
    SkillsListCommand,
    SkillsSearchCommand,
)
from app.cli_support.contracts.memory_command_contracts import (
    ContextCompactCommand,
    ContextCurateCommand,
    ContextIdCommand,
    ContextMemoryMapCommand,
    ContextRecallCommand,
    ContextReindexCommand,
    HarnessCaptureCommand,
    HarnessListCommand,
    MemoryCompactIdCommand,
    MemoryCompactListCommand,
)
from app.cli_support.contracts.runtime_command_contracts import (
    DaemonCommand,
    McpServeCommand,
    NoArgsCommand,
    ServeCommand,
    SetupCommand,
    SetupRuntimeMode,
)

__all__ = [
    "CodexMcpInstallCommand",
    "ContextCompactCommand",
    "ContextCurateCommand",
    "ContextIdCommand",
    "ContextMemoryMapCommand",
    "ContextRecallCommand",
    "ContextReindexCommand",
    "DaemonCommand",
    "FolderIdCommand",
    "FoldersCreateCommand",
    "FoldersEnsureCommand",
    "FoldersListCommand",
    "HarnessCaptureCommand",
    "HarnessListCommand",
    "HermesBundleCommand",
    "HermesConfigureCommand",
    "HermesDoctorCommand",
    "HermesInstallCommand",
    "HermesOnboardCommand",
    "HermesPolicyCommand",
    "HermesScanCommand",
    "HermesSyncCommand",
    "ItemIdCommand",
    "LibrarianAskCommand",
    "LibrarianBriefPreviewCommand",
    "LibrarianJobStatusCommand",
    "LibrarianOAuthCommand",
    "LibrarianProfileActionCommand",
    "LibrarianProfileCreateCommand",
    "LibrarianProfileUpdateCommand",
    "LibrarianProviderActionCommand",
    "LibrarianProviderConnectCodexOAuthCommand",
    "LibrarianProviderCreateCommand",
    "LibrarianRoutePreviewCommand",
    "LibraryListCommand",
    "LibrarySearchCommand",
    "McpServeCommand",
    "MemoryCompactIdCommand",
    "MemoryCompactListCommand",
    "NoArgsCommand",
    "PromptDeprecateCommand",
    "PromptDiffCommand",
    "PromptVersionCommand",
    "PromptsListCommand",
    "PromptsSearchCommand",
    "PromptsUseCommand",
    "ServeCommand",
    "SetupCommand",
    "SetupRuntimeMode",
    "SkillsListCommand",
    "SkillsSearchCommand",
    "UsageRecordCliCommand",
]
