"""Repository port for the rebuildable Obsidian graph projection."""

from __future__ import annotations

from abc import ABC, abstractmethod

from app.obsidian.domain.contracts.obsidian_graph_projection_contracts import (
    ObsidianGraphContextEvidence,
    ObsidianGraphProjection,
    ObsidianGraphProjectionIssueCount,
    ObsidianGraphProjectionState,
    ObsidianGraphRelatedNote,
)


class IObsidianGraphProjectionRepository(ABC):
    """Persist and inspect an optional Obsidian graph read model."""

    @abstractmethod
    async def start_rebuild(self, *, run_id: str, projection_version: int) -> None:
        """Prepare isolated staging state for an application-owned run.

        Args:
            run_id: Stable id generated by the application service.
            projection_version: Projection contract version being written.
        """

    @abstractmethod
    async def write_rebuild_batch(
        self,
        *,
        run_id: str,
        projection_version: int,
        batch: ObsidianGraphProjection,
    ) -> None:
        """Write one bounded batch without changing the active projection.

        Args:
            run_id: Stable application-owned run id.
            projection_version: Projection contract version being written.
            batch: One bounded projection batch.
        """

    @abstractmethod
    async def complete_rebuild(
        self,
        *,
        run_id: str,
        projection_version: int,
        issue_counts: tuple[ObsidianGraphProjectionIssueCount, ...] = (),
    ) -> None:
        """Atomically make a fully staged run active and remove stale state.

        Args:
            run_id: Stable application-owned run id.
            projection_version: Projection contract version being activated.
            issue_counts: Counted non-fatal diagnostics for the activated run.
        """

    @abstractmethod
    async def abort_rebuild(self, *, run_id: str) -> None:
        """Remove staging state for an unsuccessful run.

        Args:
            run_id: Stable application-owned run id to clean up.
        """

    @abstractmethod
    async def state(self) -> ObsidianGraphProjectionState:
        """Return active projection state and metadata.

        Returns:
            Active projection state, or explicit never-built state.
        """

    @abstractmethod
    async def related_notes(
        self,
        *,
        note_id: str,
        limit: int,
    ) -> tuple[ObsidianGraphRelatedNote, ...]:
        """Return stable ranked one-hop relations from the active projection.

        Args:
            note_id: Stable note id whose neighbors should be expanded.
            limit: Maximum number of related notes to return.

        Returns:
            Ranked active-projection relations.
        """

    @abstractmethod
    async def context_evidence(
        self,
        *,
        note_ids: tuple[str, ...],
    ) -> tuple[ObsidianGraphContextEvidence, ...]:
        """Return active-run edges limited to the recalled context ids.

        Args:
            note_ids: Recalled context ids allowed to appear in evidence.

        Returns:
            Active-run evidence whose endpoints are both allowed.
        """

    async def snapshot(self) -> ObsidianGraphProjection:
        """Return the active projection for graph consumers.

        Returns:
            Current active nodes and edges ordered by stable identity.
        """
        return (await self.state()).projection
