"""Canonical frontmatter and Markdown rendering for acquired skill artifacts."""

from __future__ import annotations

from uuid import NAMESPACE_URL, uuid5

from app.librarian.application.skill_artifact_value_policy import (
    _bullet_or_none,
    _clean_items,
    _evidence_item_payloads,
    _json_block,
)
from app.librarian.domain.contracts.skill_acquisition_contracts import (
    SkillAcquisitionArtifact,
)
from app.librarian.domain.entities.skill_acquisition_job import SkillAcquisitionJob
from app.shared.types.extra_types import JSONObject


def _skill_note_id(job_id: str) -> str:
    return str(uuid5(NAMESPACE_URL, f"alexandria-hermes:skill:{job_id}"))


def _skill_tags(artifact: SkillAcquisitionArtifact) -> list[str]:
    tags = ["skill-acquisition", *artifact.tags]
    deduplicated: list[str] = []
    for tag in tags:
        normalized = tag.strip()
        if normalized and normalized not in deduplicated:
            deduplicated.append(normalized)
    return deduplicated


def _skill_frontmatter(
    *,
    job: SkillAcquisitionJob,
    artifact: SkillAcquisitionArtifact,
) -> JSONObject:
    return {
        "version": artifact.version,
        "purpose": artifact.purpose,
        "when_to_use": [],
        "when_not_to_use": [],
        "required_tools": _clean_items(artifact.required_tools),
        "risk_level": artifact.risk_level.value,
        "created_by": artifact.created_by_name or "librarian",
        "source_job_id": job.id,
        "source_prompt_id": "librarian_operating_prompt_v0_1",
        "evidence_urls": _clean_items(artifact.evidence_urls),
        "evidence_items": _evidence_item_payloads(artifact),
        "source_summary": artifact.source_summary,
        "created_at": job.created_at.isoformat(),
        "reviewed_at": None,
        "supersedes": [],
        "requested_status": artifact.status.value,
        "activate_requested": artifact.activate,
    }


def _skill_markdown_body(
    *,
    job: SkillAcquisitionJob,
    artifact: SkillAcquisitionArtifact,
) -> str:
    usage = artifact.summary or artifact.purpose
    lines = [
        f"# {artifact.title.strip()}",
        "",
        "## 목적",
        artifact.purpose.strip(),
        "",
        "## 언제 사용해야 하는가",
        _bullet_or_none([usage]),
        "",
        "## 언제 사용하지 말아야 하는가",
        _bullet_or_none(
            [
                "필요 도구나 권한이 없으면 적용하지 말고 blocker로 보고한다.",
                "현재 task의 risk tolerance를 초과하면 human review 전 자동 실행하지 않는다.",
            ]
        ),
        "",
        "## 입력/사전조건",
        _input_contract(artifact),
        "",
        "## 단계별 절차 (Procedure)",
        artifact.content.strip(),
        "",
        "## 출력 계약",
        _output_contract(artifact),
        "",
        "## 실패 모드와 복구",
        _bullet_or_none(
            [
                "required tool이 없으면 대체 절차를 추정하지 말고 missing-tool blocker를 반환한다.",
                "절차 검증이 실패하면 생성된 산출물을 사용하지 말고 evidence와 입력 조건을 재확인한다.",
            ]
        ),
        "",
        "## 안전·권한·비밀정보 가드레일",
        _bullet_or_none(
            [
                f"risk_level: {artifact.risk_level.value}",
                "status: draft; human review is required before active promotion",
                "credential, token, private raw log, 개인정보를 skill 본문이나 evidence에 저장하지 않는다.",
            ]
        ),
        "",
        "## 사용 예시",
        artifact.usage_example.strip() if artifact.usage_example else "- none provided",
        "",
        "## Evidence와 claim mapping",
        _evidence_claim_mapping(artifact),
        "",
        "## 현재 task에 적용하는 next steps",
        _next_steps(job=job, artifact=artifact),
        "",
        "## 버전/변경 이력",
        _bullet_or_none(
            [
                f"version: {artifact.version}",
                f"created_from_job: {job.id}",
                "initial draft generated by skill acquisition completion",
            ]
        ),
        "",
        "## Acquisition context",
        f"- job_id: {job.id}",
        f"- agent: {job.agent_name}",
        f"- project: {job.project or 'default'}",
    ]
    if job.task_summary:
        lines.append(f"- task_summary: {job.task_summary}")
    return "\n".join(lines).strip() + "\n"


def _input_contract(artifact: SkillAcquisitionArtifact) -> str:
    items = _clean_items(artifact.required_tools)
    lines = ["- required_tools: " + (", ".join(items) if items else "none declared")]
    if artifact.input_schema:
        lines.extend(["- input_schema:", _json_block(artifact.input_schema)])
    else:
        lines.append("- input_schema: none provided")
    return "\n".join(lines)


def _output_contract(artifact: SkillAcquisitionArtifact) -> str:
    if artifact.output_schema:
        return "- output_schema:\n" + _json_block(artifact.output_schema)
    return _bullet_or_none(
        [
            "현재 task에 적용 가능한 절차, 산출물, 검증 또는 blocker를 명확히 반환한다.",
            "불확실하거나 실행 불가능한 조건은 limitations와 next steps에 남긴다.",
        ]
    )


def _evidence_claim_mapping(artifact: SkillAcquisitionArtifact) -> str:
    evidence_items = _evidence_item_payloads(artifact)
    if evidence_items:
        lines: list[str] = []
        for item in evidence_items:
            supports_claims = item.get("supports_claims")
            claims = (
                [claim for claim in supports_claims if isinstance(claim, str) and claim]
                if isinstance(supports_claims, list)
                else []
            )
            if not claims:
                claims = ["No claim mapping provided."]
            title = item.get("title")
            source_kind = item.get("source_kind")
            publisher = item.get("publisher_or_repository")
            freshness = item.get("freshness")
            lines.append(f"- {item['url_or_path']} supports: {', '.join(claims)}")
            if isinstance(title, str) and title:
                lines.append(f"  - title: {title}")
            if isinstance(source_kind, str) and source_kind:
                lines.append(f"  - source_kind: {source_kind}")
            if isinstance(publisher, str) and publisher:
                lines.append(f"  - publisher_or_repository: {publisher}")
            if isinstance(freshness, str) and freshness:
                lines.append(f"  - freshness: {freshness}")
        return "\n".join(lines)
    evidence = _clean_items(artifact.evidence_urls)
    source_summary = (artifact.source_summary or "No source summary provided.").strip()
    if not evidence:
        return _bullet_or_none(
            [
                "evidence: none provided",
                f"source_summary: {source_summary}",
                "external claims require reviewer verification before active promotion",
            ]
        )
    return "\n".join(f"- {url} supports: {source_summary}" for url in evidence)


def _next_steps(*, job: SkillAcquisitionJob, artifact: SkillAcquisitionArtifact) -> str:
    steps = _clean_items(artifact.next_steps)
    if steps:
        return _bullet_or_none(steps)
    if job.task_summary:
        return _bullet_or_none([f"Resume task: {job.task_summary}"])
    return "- Review this draft skill, then apply it only after prerequisites are met."
